### ISSUE TITLE
 Mismatch in Error Code and Message for starknet_traceTransaction

### ISSUE THREAD

**Issue by wojciechos** [NethermindEth/juno#1076]
The error response for `starknet_traceTransaction` does not match the specification when provided with an invalid `transaction_hash`.

**Steps to reproduce:**

1. Send a request to the starknet_traceTransaction method with the following payload:
```{
    "jsonrpc": "2.0",
    "method": "starknet_traceTransaction",
    "params": {
        "transaction_hash": "0x11d9ca99dcd495081773767ff424822cf32c389c7fe38f2d965c1ff0c48064442"
    },
    "id": 1
}
```
**Expected Result:**
According to [spec](https://github.com/starkware-libs/starknet-specs/blob/0e859ff905795f789f1dfd6f7340cdaf5015acc8/api/starknet_trace_api_openrpc.json#L33C50-L33C50) should be:

```{
    "jsonrpc": "2.0",
    "error": {
        "code": 25,
        "message": "Invalid transaction hash"
    },
    "id": 1
}
```
**Actual Result:**
```{
    "jsonrpc": "2.0",
    "error": {
        "code": -32602,
        "message": "Invalid Params",
        "data": "can't fit in felt: 0x11d9ca99dcd495081773767ff424822cf32c389c7fe38f2d965c1ff0c48064442"
    },
    "id": 1
}
```

**Comment by omerfirmak** [comment]
This is a non-issue.

Spec [defines](https://github.com/starkware-libs/starknet-specs/blob/0e859ff905795f789f1dfd6f7340cdaf5015acc8/api/starknet_api_openrpc.json#L1266-L1271) field elements as strings starting with "0x" and at max 62 hexadecimal digits following.

Since "0x11d9ca99dcd495081773767ff424822cf32c389c7fe38f2d965c1ff0c48064442" has more than 62 digits, it is not a valid field element. Since it violates the spec, we return an "Invalid Param" error.

If the transaction hash was a valid felt, but we couldnt find a transaction matching that hash, we would return the error you are expecting. So try with "0x0" as the transaction hash and you should be able to replicate that.

https://github.com/NethermindEth/juno/blob/main/rpc/handlers.go#L1114

**Comment by wojciechos** [comment]
Ok, make sense, but still for valid transactions (like 0x0) we return:
```
{
    "jsonrpc": "2.0",
    "error": {
        "code": 29,
        "message": "Transaction hash not found"
    },
    "id": 1
}
```
while according to spec should be:
```    "jsonrpc": "2.0",
    "error": {
        "code": 25,
        "message": "Invalid transaction hash"
    },
    "id": 1
}
```

**Comment by omerfirmak** [comment]
Ah, got it. I confused "Invalid transaction hash" with "Transaction hash not found"
