### ISSUE TITLE
Connect to node

### ISSUE THREAD

**Issue by ozanbayram** [NethermindEth/juno#1422]
When I try to connect to the node without the "--http-host 0.0.0.0" parameter, I cannot connect. This parameter has been forgotten to be added to the code snippet in the "Run Juno Using Snapshot" section of the readme file.
```
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host xx.xxx.xxx.xx:6060 ssl:default [Connect call failed ('xx.xxx.xxx.xx', 6060)]
 raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 111] Connect call failed ('xx.xxx.xxx.xx', 6060)
```

Also, even though the default parameter for "--http-host" is localhost, I couldn't connect from localhost without "--http-host 0.0.0.0".
```
raise ConnectionResetError("Cannot write to closing transport")
ConnectionResetError: Cannot write to closing transport
The above exception was the direct cause of the following exception:
aiohttp.client_exceptions.ClientOSError: [Errno None] Can not write request body for http://localhost:6060
```

**Comment by wojciechos** [comment]
Hey, thanks for rising this! 
Just a small explanation: localhost inside a Docker container isn't the same as the localhost on your actual machine. When Juno runs inside Docker without --http-host 0.0.0.0, it's exposing RPC on the container's localhost, not your machine's. That's why you can't access it from outside the Docker container.
