### ISSUE TITLE
Proccess Handler Bug

### ISSUE THREAD

**Issue by stdevAdrianPaez** [NethermindEth/juno#205]
**Describe the bug**
When we initialize the database services on the `root.go` file, like this:

```golang
handler.Add("TransactionService", services.TransactionService.Run, services.TransactionService.Close)
handler.Add("BlockService", services.BlockService.Run, services.BlockService.Close)
```
the application doesn't stop because it can't ever reach the `handler.Close()` line because they are stuck on the`select{}` line on the `handler.Run()`.

**To Reproduce**
1. Go to `cmd/juno/cli/root.go`
2. Paste this code on line 59-60 (after RPC initialization and before `log.Default.Info("Starting all processes...")` line)

```golang
handler.Add("TransactionService", services.TransactionService.Run, services.TransactionService.Close)
handler.Add("BlockService", services.BlockService.Run, services.BlockService.Close)
```
3. Make sure the RPC is disabled on the configuration file (we only want the database services active).
4. Run Juno with `make all` command
5. You may see something like this:
```
2022-06-08T09:22:32.988-0400    INFO    cli/root.go:109 Using config file:      {"File": "/path/to/juno/juno.yaml"}
2022-06-08T09:22:32.988-0400    INFO    cli/root.go:127 Config values.  {"Database Path": "/path/to/juno", "Rpc Port": 8080, "Rpc Enabled": false}
2022-06-08T09:22:32.988-0400    INFO    cli/root.go:64  Starting all processes...
2022-06-08T09:22:32.988-0400    INFO    Block Service   services/service.go:34  Service started
2022-06-08T09:22:32.989-0400    INFO    Transaction Service     services/service.go:34  Service started
```
6. After that the only way to close the app is with a SIGTERM or SIGKILL

**Expected behavior**
I expect the application to exit immediately because the database services are "internal" services, so they cannot block the application if any other service, other than a primary one (such as RPC), is not running.

**Comment by smishy05** [comment]
This is how the application functions as of now:

1. Only `RPC` disabled - Juno runs.
2. Only `REST` disabled - Juno runs.
3. Only `Starknet` disabled - Juno is blocked.
4. `RPC` and `REST` disabled - Juno runs.
5. `Starknet` disabled with any of these two - Juno is blocked.
6. All three disabled - Juno is blocked.

Do we want Juno to exit in all of the these scenarios? 

As much as I could figure out, we want the app to exit if `Starknet` is disabled. Please correct me if I am wrong and please elaborate on the expected behavior a bit more.
