### ISSUE TITLE
Remove Panics of the app

### ISSUE THREAD

**Issue by stdevMac** [NethermindEth/juno#227]
**Describe the bug**
Each time the app encounters an error that we should not recover, instead of Panic, and printing all the stack traces, we should handle that error, print an Error log, and close properly the app.

There should not exist `panic`,

**Comment by v4lproik** [comment]
As per as #264 it would be nice to extend a config env variable (eg. juno_env="prod") so zap [dpanic](https://github.com/uber-go/zap/blob/master/FAQ.md#whats-dpanic) can be used. Panic behaviour is different whether the logger is initiated with a "development" or a "production" setting. Documentation says:
`DPanic stands for "panic in development." In development, it logs at PanicLevel; otherwise, it logs at ErrorLevel. DPanic makes it easier to catch errors that are theoretically possible, but shouldn't actually happen, without crashing in production.`

This would highly improve logging.

**Comment by stdevMac** [comment]
That sounds great! if you want to take a look at that is more than welcome!

**Comment by v4lproik** [comment]
Alright! I'll get on with it then!
