### ISSUE TITLE
Optimize the DivMod function

### ISSUE THREAD

**Issue by joshklop** [NethermindEth/juno#273]
The `divMod` function in [points.go](https://github.com/NethermindEth/juno/blob/64ec93002abdc74e44bf6b20995a192bb07236fd/pkg/crypto/pedersen/points.go#L2050-L2058) is a major bottleneck when applying state diffs to the local database. Right now, we are using `big.Int`s, which are inefficient.

**Solution**

An implementation of [Lehmer's GCD algorithm](https://en.wikipedia.org/wiki/Lehmer%27s_GCD_algorithm) using the felt package. This is the same algorithm that the `big` package uses, but our `felt.Felt`s should vastly outperform `big.Int`s. 

Note that we don't want to use the modular arithmetic functions provided by the felt package when computing the GCD. Since our felts are just `[4]uint64` underneath, we can use the very fast [uint256](https://github.com/holiman/uint256) library instead.

**Alternatives Considered**

I have tried to implement this using [`gmp.Int`](https://github.com/ncw/gmp) as a drop-in replacement for `big.Int`, but it was slower than using `big.Int`s directly (probably due to the increase in allocations from felt -> big.Int -> gmp.Int -> big.Int -> felt). 

I also considered porting the [`igcdex`](https://github.com/sympy/sympy/blob/6ea48db2bd108a0c5b3c53aa2f1ef9e5d617bf3c/sympy/core/numbers.py#L445-L488) function from the Python [reference implementation](https://github.com/starkware-libs/cairo-lang/blob/2abd303e1808612b724bc1412b2b5babd04bb4e7/src/starkware/python/math_utils.py#L27), but it implements Euclid's GCD algorithm, which is slower than Lehmer's algorithm for big numbers.

**Comment by ayushm2003** [comment]
some of the discussions we had on this -

1. The [Inverse](https://github.com/NethermindEth/juno/blob/86340bef8f9b2c8dbdc6ffeea2da8f151829520e/pkg/felt/felt.go#L1157) function provided by the `felt` package doesn't work as a replacement for Lehmer's gcd function to compute inverses, since it computes the results modulo p, which changes the results of the [product](https://github.com/NethermindEth/juno/blob/main/pkg/crypto/pedersen/points.go#L2057)
2. The problem with implementing Lehmer's gcd for felts is that we still need a way to handle negative values with felts. Maybe, this can be achieved by using a new variable to keep track of the felt's sign whenever it under/over flows.

This issue is on hold for the moment.
