### ISSUE TITLE
Add a new log level between info and warn

### ISSUE THREAD

**Issue by ninja342** [NethermindEth/juno#972]
I am using Juno very aggressively and logging all rpc requests makes huge log files: 9gb log file in 2 weeks. I have tried to set log level to warn but this time can't see the block updates. I suggest adding a new log level between warn and info that logs all other info level logs except rpc requests.

**Comment by omerfirmak** [comment]
We can demote RPC logs to be Debug logs

**Comment by ninja342** [comment]
Great idea

**Comment by joshklop** [comment]
Thanks for the feedback @ninja342.

> I am using Juno very aggressively

Curious if you have any thoughts on how we can improve Juno? Would love to learn more about your use case.

**Comment by ninja342** [comment]
Hey @joshklop thanks for your interest. I have 2 servers running Juno for checking amm pools to find arbitrage opportunities. It is very important for my case Juno to fetch pending block as fast as possible. If you can somehow improve the fetching speed of pending block it will be very good for my use case.

**Comment by joshklop** [comment]
Thanks for the context. You've probably already done this, but minimizing the `--pending-poll-interval` param will make Juno request the pending block from the gateway more frequently. Otherwise, Juno is constrained by network latency and the gateway's speed and uptime.

The 0.4.1 release includes an optimization to the block import process, so that should also speed up applying pending block state.
