### ISSUE TITLE
Warn the user for not having enough disk space before syncing

### ISSUE THREAD

**Issue by IronGauntlets** [NethermindEth/juno#993]

**Comment by Sah314** [comment]
@IronGauntlets can you provide more information about the issue? Thanks

**Comment by IronGauntlets** [comment]
cc: @eliotstock

**Comment by eliotstock** [comment]
This is one thing that stood out as a missing feature in the "first run" experience.

As a new user running Juno for the first time, I may have no idea how big the chain is so far. I want to know how much disk space I can expect Juno to use today and up to six months into the future so that I can a) first ensure I have a big enough disk/partition and b) don't waste days attempting to sync on a machine (or choice of disk or partition for `--db-path` on that machine) that is probably going to get filled up.

It would be nice if the estimated total storage required is not hard-coded, but grows with what we're seeing in the wild without us having to make code or config changes.

We should add some safety margin over the total storage because having a disk that's 99.9% full is not a good state to be in either.

This is most relevant for mainnet but nice to have for the testnets too.

Implementing this is somewhat complicated by the snapshots. If the extracted snapshot tarball is 36.5 GB, we need to estimate how much we add to that for the blocks that need to be synced that come after the snapshot. And the snapshot will (for the moment at least) have been downloaded and extracted by the user before the `juno` process runs.

For the moment, the chain is small enough that relatively few users will run out of disk space, even if running on a laptop. Nonetheless the logging should communicate that everything looks ok for disk space as early as possible, then it's one point of anxiety I can relax about as a new user.

Short term workaround: add some hardware requirements (including disk space) to the `README.md`.

**Comment by Sah314** [comment]
can you please assign it to me?

**Comment by eliotstock** [comment]
Oh. No, I can't. Seems I don't have the right role in the repo. Will fix that first.

**Comment by eliotstock** [comment]
In the meantime @IronGauntlets can assign it to you.
